name: qrscanner
description: A modern QR scanner application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  flutter_riverpod: ^2.4.9
  
  # UI Components
  flutter_animate: ^4.3.0  # For smooth animations
  google_fonts: ^6.1.0     # Modern typography
  flutter_svg: ^2.0.9      # SVG support
  shimmer: ^3.0.0         # Loading effects
  lottie: ^2.7.0          # Animation files
  flutter_screenutil: ^5.9.0  # Responsive UI
  
  # Navigation
  go_router: ^13.0.0      # Modern routing
  
  # Storage & Data
  shared_preferences: ^2.2.2
  isar: ^3.1.0           # Modern database
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1
  
  # Functionality
  mobile_scanner: ^3.5.2   # QR scanning
  flutter_inappwebview: ^5.8.0
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  dio: ^5.4.0             # HTTP client
  
  # UI Utilities
  flutter_hooks: ^0.20.3
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/Technocrafts-logo.png
    - assets/animations/
    - assets/icons/

flutter_native_splash:
  color: "#E53935"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#E53935"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"